# Generated by Django 5.0.7 on 2024-07-28 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_alter_tasks_due_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
